/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ComponentOverviewEntry struct {
	// 1-None/Negligible, 2-Unknown, 3-Low, 4-Medium, 5-High
	Severity int32 `json:"severity,omitempty"`
	// number of the components with certain severity.
	Count int32 `json:"count,omitempty"`
}
