/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type Search struct {
	// Search results of the projects that matched the filter keywords.
	Project []Project `json:"project,omitempty"`
	// Search results of the repositories that matched the filter keywords.
	Repository []SearchRepository `json:"repository,omitempty"`
	// Search results of the charts that macthed the filter keywords.
	Chart []SearchResult `json:"chart,omitempty"`
}
