/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

// The registry info contains the base info and capability declarations of the registry
type RegistryInfo struct {
	// The registry type
	Type_ string `json:"type,omitempty"`
	// The description
	Description string `json:"description,omitempty"`
	// The filters that the registry supports
	SupportedResourceFilters []FilterStyle `json:"supported_resource_filters,omitempty"`
	// The triggers that the registry supports
	SupportedTriggers []string `json:"supported_triggers,omitempty"`
}
