/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ProjectReq struct {
	// The name of the project.
	ProjectName string `json:"project_name,omitempty"`
	// The metadata of the project.
	Metadata *ProjectMetadata `json:"metadata,omitempty"`
}
