/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

// The namespace of registry
type Namespace struct {
	// The name of namespace
	Name string `json:"name,omitempty"`
	// The metadata of namespace
	Metadata *interface{} `json:"metadata,omitempty"`
}
