/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ConfigurationsScanAllPolicy struct {
	// The type of scan all policy, currently the valid values are \"none\" and \"daily\"
	Type_     string                                `json:"type,omitempty"`
	Parameter *ConfigurationsScanAllPolicyParameter `json:"parameter,omitempty"`
}
