/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type AdminJobScheduleObj struct {
	// The schedule type. The valid values are hourly, daily， weekly, custom and None. 'None' means to cancel the schedule.
	Type_ string `json:"type,omitempty"`
	// A cron expression, a time-based job scheduler.
	Cron string `json:"cron,omitempty"`
}
