/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type DetailedTag struct {
	// The digest of the tag.
	Digest string `json:"digest,omitempty"`
	// The name of the tag.
	Name string `json:"name,omitempty"`
	// The size of the image.
	Size int32 `json:"size,omitempty"`
	// The architecture of the image.
	Architecture string `json:"architecture,omitempty"`
	// The os of the image.
	Os string `json:"os,omitempty"`
	// The version of docker which builds the image.
	DockerVersion string `json:"docker_version,omitempty"`
	// The author of the image.
	Author string `json:"author,omitempty"`
	// The build time of the image.
	Created string `json:"created,omitempty"`
	// The signature of image, defined by RepoSignature. If it is null, the image is unsigned.
	Signature    *interface{}             `json:"signature,omitempty"`
	ScanOverview *DetailedTagScanOverview `json:"scan_overview,omitempty"`
	// The label list.
	Labels []Label `json:"labels,omitempty"`
}
