/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type ConfigurationsResponse struct {
	// The auth mode of current system, such as \"db_auth\", \"ldap_auth\"
	AuthMode *StringConfigItem `json:"auth_mode,omitempty"`
	// The sender name for Email notification.
	EmailFrom *StringConfigItem `json:"email_from,omitempty"`
	// The hostname of SMTP server that sends Email notification.
	EmailHost *StringConfigItem `json:"email_host,omitempty"`
	// The port of SMTP server.
	EmailPort *IntegerConfigItem `json:"email_port,omitempty"`
	// By default it's empty so the email_username is picked.
	EmailIdentity *StringConfigItem `json:"email_identity,omitempty"`
	// The username for authenticate against SMTP server.
	EmailUsername *StringConfigItem `json:"email_username,omitempty"`
	// When it's set to true the system will access Email server via TLS by default.  If it's set to false, it still will handle \"STARTTLS\" from server side.
	EmailSsl *BoolConfigItem `json:"email_ssl,omitempty"`
	// Whether or not the certificate will be verified when Harbor tries to access the email server.
	EmailInsecure *BoolConfigItem `json:"email_insecure,omitempty"`
	// The URL of LDAP server.
	LdapUrl *StringConfigItem `json:"ldap_url,omitempty"`
	// The Base DN for LDAP binding.
	LdapBaseDn *StringConfigItem `json:"ldap_base_dn,omitempty"`
	// The filter for LDAP binding.
	LdapFilter *StringConfigItem `json:"ldap_filter,omitempty"`
	// 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
	LdapScope int32 `json:"ldap_scope,omitempty"`
	// The attribute which is used as identity for the LDAP binding, such as \"CN\" or \"SAMAccountname\"
	LdapUid *StringConfigItem `json:"ldap_uid,omitempty"`
	// The DN of the user to do the search.
	LdapSearchDn string `json:"ldap_search_dn,omitempty"`
	// timeout in seconds for connection to LDAP server.
	LdapTimeout *IntegerConfigItem `json:"ldap_timeout,omitempty"`
	// The attribute which is used as identity of the LDAP group, default is cn.
	LdapGroupAttributeName *StringConfigItem `json:"ldap_group_attribute_name,omitempty"`
	// The base DN to search LDAP group.
	LdapGroupBaseDn *StringConfigItem `json:"ldap_group_base_dn,omitempty"`
	// The filter to search the ldap group.
	LdapGroupSearchFilter *StringConfigItem `json:"ldap_group_search_filter,omitempty"`
	// The scope to search ldap. '0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE'
	LdapGroupSearchScope *IntegerConfigItem `json:"ldap_group_search_scope,omitempty"`
	// Specify the ldap group which have the same privilege with Harbor admin.
	LdapGroupAdminDn *StringConfigItem `json:"ldap_group_admin_dn,omitempty"`
	// This attribute restricts what users have the permission to create project.  It can be \"everyone\" or \"adminonly\".
	ProjectCreationRestriction *StringConfigItem `json:"project_creation_restriction,omitempty"`
	// 'docker push' is prohibited by Harbor if you set it to true.
	ReadOnly *BoolConfigItem `json:"read_only,omitempty"`
	// Whether the Harbor instance supports self-registration.  If it's set to false, admin need to add user to the instance.
	SelfRegistration *BoolConfigItem `json:"self_registration,omitempty"`
	// The expiration time of the token for internal Registry, in minutes.
	TokenExpiration *IntegerConfigItem `json:"token_expiration,omitempty"`
	// Whether or not the certificate will be verified when Harbor tries to access a remote Harbor instance for replication.
	VerifyRemoteCert *BoolConfigItem              `json:"verify_remote_cert,omitempty"`
	ScanAllPolicy    *ConfigurationsScanAllPolicy `json:"scan_all_policy,omitempty"`
}
