/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

// The components overview of the image.
type DetailedTagScanOverviewComponents struct {
	// Total number of the components in this image.
	Total int32 `json:"total,omitempty"`
	// List of number of components of different severities.
	Summary []ComponentOverviewEntry `json:"summary,omitempty"`
}
