/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type User struct {
	// The ID of the user.
	UserId       int32  `json:"user_id,omitempty"`
	Username     string `json:"username,omitempty"`
	Email        string `json:"email,omitempty"`
	Password     string `json:"password,omitempty"`
	Realname     string `json:"realname,omitempty"`
	Comment      string `json:"comment,omitempty"`
	Deleted      bool   `json:"deleted,omitempty"`
	RoleName     string `json:"role_name,omitempty"`
	RoleId       int32  `json:"role_id,omitempty"`
	HasAdminRole bool   `json:"has_admin_role,omitempty"`
	ResetUuid    string `json:"reset_uuid,omitempty"`
	Salt         string `json:"Salt,omitempty"`
	CreationTime string `json:"creation_time,omitempty"`
	UpdateTime   string `json:"update_time,omitempty"`
}
