/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type EmailServerSetting struct {
	// The host of email server.
	EmailHost string `json:"email_host,omitempty"`
	// The port of email server.
	EmailPort int32 `json:"email_port,omitempty"`
	// The username of email server.
	EmailUsername string `json:"email_username,omitempty"`
	// The password of email server.
	EmailPassword string `json:"email_password,omitempty"`
	// Use ssl/tls or not.
	EmailSsl bool `json:"email_ssl,omitempty"`
	// The dentity of email server.
	EmailIdentity string `json:"email_identity,omitempty"`
}
