/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

type Storage struct {
	// Total volume size.
	Total int64 `json:"total,omitempty"`
	// Free volume size.
	Free int64 `json:"free,omitempty"`
}
