/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

// The health status of component
type ComponentHealthStatus struct {
	// The component name
	Name string `json:"name,omitempty"`
	// The health status of component
	Status string `json:"status,omitempty"`
	// (optional) The error message when the status is \"unhealthy\"
	Error_ string `json:"error,omitempty"`
}
