/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.7.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harbor

// Another chart the chart depends on
type Dependency struct {
	// The name of the chart denpendency
	Name string `json:"name"`
	// The version of the chart dependency
	Version string `json:"version"`
	// The URL to the repository
	Repository string `json:"repository,omitempty"`
}
